### ISSUE TITLE
Перестало работать после обновлений

### ISSUE THREAD

**Issue by dganic** [mdevaev/emonoda#43]
Не сразу заметил что после обновлений сменилось название бинарника с emfetch на emupdate)
Но работать все равно отказывается:

# I: Client transmission is ready       
Traceback (most recent call last):
  File "/usr/bin/emupdate", line 9, in <module>
    load_entry_point('emonoda==2.0.14', 'console_scripts', 'emupdate')()
  File "/usr/lib/python3.5/site-packages/emonoda/apps/emupdate.py", line 433, in main
    raise SystemExit(1)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.5/site-packages/emonoda/apps/__init__.py", line 125, in get_configured_log
    yield log
  File "/usr/lib/python3.5/site-packages/emonoda/apps/emupdate.py", line 433, in main
    raise SystemExit(1)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.5/site-packages/emonoda/apps/__init__.py", line 125, in get_configured_log
    yield log
  File "/usr/lib/python3.5/site-packages/emonoda/apps/emupdate.py", line 384, in main
    log=log_stderr,
  File "/usr/lib/python3.5/site-packages/emonoda/apps/__init__.py", line 156, in get_configured_trackers
    raise RuntimeError("No trackers to init")

**Comment by mdevaev** [comment]
В конфиге переименуйте `fetchers:` в `trackers:`.
