### ISSUE TITLE
Поддержка нового API rTorrent >= 0.9.6

### ISSUE THREAD

**Issue by omgiafs** [mdevaev/emonoda#46]
Наконец-то дошли руки установить emonoda. Конфиг заполнил, трекеры прописал, запускаю и получаю:

```
www@nas:~$ rtorrent -h
Rakshasa's BitTorrent client version 0.9.6.

www@nas:~$ emupdate
# E: Can't init client rtorrent: Fault(<Fault -506: "Method 'set_xmlrpc_size_limit' not defined">)
Traceback (most recent call last):
  File "/home/www/.local/bin/emupdate", line 9, in <module>
    load_entry_point('emonoda==2.0.18', 'console_scripts', 'emupdate')()
  File "/home/www/.local/lib/python3.4/site-packages/emonoda/apps/emupdate.py", line 369, in main
    log=log_stderr,
  File "/home/www/.local/lib/python3.4/site-packages/emonoda/apps/__init__.py", line 138, in get_configured_client
    client = cls(**config.client)
  File "/home/www/.local/lib/python3.4/site-packages/emonoda/plugins/clients/rtorrent.py", line 61, in __init__
    self._server.set_xmlrpc_size_limit(xmlrpc_size_limit)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1089, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1419, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1131, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1147, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1318, in parse_response
    return u.close()
  File "/usr/lib/python3.4/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -506: "Method 'set_xmlrpc_size_limit' not defined">
```

В rtorrent 0.9.6 относительно 0.9.4 поменялся синтаксис команд, и старые команды вроде как  [автоматически должны преобразовываться в новые](https://github.com/rakshasa/rtorrent/blob/master/src/main.cc#L591), но это не так :) Конфиг rtorrent после апгрейда на 0.9.6 надо было править руками, да и диагностика проблемы заняла порядочно времени (я пока не шибко красноглаз).

Как я понял, rtorrent 0.9.6 через XMLRPC отвечает, что не знает метода **set_xmlrpc_size_limit**. В rtorrent 0.9.6 (и, надеюсь, далее) этот метод называется **network.xmlrpc.size_limit.set**.

**Comment by mdevaev** [comment]
Это у вас точно 0.9.6, или может это сборка альфы 1.0 с неизмененной версией? Дело в том, что синтаксис поменялся именно в альфе, я уже смотрел некоторое время назад. У меня самого стоит 0.9.6 и все работает. Откуда вы взяли свой пакет?

**Comment by omgiafs** [comment]
Хм. Наверное альфа. Я с исходников канпелял щас посмотрю... 06.01 2016. 
Еще бы вспомнить, где я их взял... Вспомнил. [Тут](http://rtorrent.net/downloads/rtorrent-0.9.6.tar.gz)!
Если надо было брать из Git - прошу пардону, я таких тонкостей не знал. ДУмаю - лежит архив с версией, значит стабильная, альфы никакой в названии нет.

**Comment by mdevaev** [comment]
Вот тут есть арчевый пакет, там написано, откуда брать исходники и с какими опциями собирать, посмотрите: https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rtorrent

**Comment by omgiafs** [comment]
Спасибо, пошел напрягать компиляторы...
Но, черт побери, на [https://rakshasa.github.io/rtorrent/](https://rakshasa.github.io/rtorrent/) ссылка на этот же архив...
Тем не менее этот архив с версией, скачанной с [https://codeload.github.com/rakshasa/rtorrent/tar.gz/0.9.6](https://codeload.github.com/rakshasa/rtorrent/tar.gz/0.9.6) расходятся.

Но в гитхабовской версии в папке `src` всё то же самое, только отсутствуют файлы `Makefile.in`. Код без изменений.
Буду посмотреть, наши руки не для скуки.

**Comment by mdevaev** [comment]
Нет, не должно. Подозреваю, что у вас libtorrent не той версии. Т.е. компилять надо и то, и другое. Попробуйте.
Энивей, я уже собирался делать поддержку нового апи, потому что у автора все потихоньку движется к релизу. Вы потестируете, новую мою реализацию, если что?

**Comment by omgiafs** [comment]
Потестирую, не вопрос. Мне бы заставить это всё работать для начала :)
Пошел откатываться и компилять...

**Comment by omgiafs** [comment]
Ну всё. Заработало. Спасибо большое.
Дело было вовсе на в emonod'е...

**Comment by mdevaev** [comment]
Отлично. В любом случае, поддержку нового API я сделаю.
